In [1]:
import numpy as np
from sklearn.decomposition import PCA

In [29]:
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
X = np.random.rand(6,5)

In [41]:
pca = PCA(n_components=2)
pca.fit_transform(X)

array([[-0.39042694, -0.06408856],
       [-0.01381029,  0.690777  ],
       [ 0.74816362,  0.10691187],
       [-0.54295767,  0.10152551],
       [ 0.37205316, -0.33911042],
       [-0.17302188, -0.49601539]])

In [50]:
print(pca.explained_variance_)

[0.23510718 0.17280899]


In [51]:
print(pca.components_)

[[-0.67892781  0.38451219  0.5343114   0.2647425  -0.18875947]
 [ 0.54773185  0.71342944  0.05073172 -0.04197721 -0.43205609]]


# PCA from scratch

In [71]:
class HPCA:
    def __init__(self, n_components):
        self.n_components = n_components
    def fit_transform(self, X):
        # normalization
        x_mean = np.mean(X, axis=0)
        # x_std = np.std(X, axis=0)
        X = (X-x_mean)#/x_std
        # covariance
        cov_matrix = np.cov(X, rowvar=False)
        # eigen value decomposition
        eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
        # sort eigenvalues
        order = np.argsort(eigenvalues)[::-1]
        eigenvalues = eigenvalues[order]
        eigenvectors = eigenvectors[:, order]
        # topk dimensions
        self.principal_components = eigenvectors[:,0:self.n_components]
        self.explained_variance = eigenvalues[:self.n_components]
        # transform X
        X_new = X @ self.principal_components
        return X_new

In [72]:
hpca = HPCA(n_components=2)
hpca.fit_transform(X)

array([[-0.39042694,  0.06408856],
       [-0.01381029, -0.690777  ],
       [ 0.74816362, -0.10691187],
       [-0.54295767, -0.10152551],
       [ 0.37205316,  0.33911042],
       [-0.17302188,  0.49601539]])

In [73]:
hpca.explained_variance

array([0.23510718, 0.17280899])

In [75]:
hpca.principal_components.T

array([[-0.67892781,  0.38451219,  0.5343114 ,  0.2647425 , -0.18875947],
       [-0.54773185, -0.71342944, -0.05073172,  0.04197721,  0.43205609]])