In [1]:
import torch
import numpy as np
from torch import nn
import torch.nn.functional as F

In [2]:
epsilon = 1e-6

# Tanh

In [4]:
def tanh(x):
    return (np.exp(x)-np.exp(-x))/(np.exp(x)+np.exp(-x))

In [5]:
x = torch.randn(5, requires_grad=False)
y = nn.Tanh()(x).numpy()
y_ = tanh(x.numpy())
print(y-y_)

[-6.7055225e-08 -5.9604645e-08  5.9604645e-08  5.9604645e-08
 -1.1175871e-08]


# Sigmoid

In [6]:
def sigmoid(x):
    return 1. / (1. + np.exp(-x))

In [7]:
x = torch.randn(5, requires_grad=False)
y = nn.Sigmoid()(x).numpy()
y_ = sigmoid(x.numpy())
print(y-y_)

[ 5.9604645e-08 -2.9802322e-08  0.0000000e+00  0.0000000e+00
  0.0000000e+00]


# SoftMax

In [8]:
def softmax(x, axis=None):
    return np.exp(x)/np.exp(x).sum(axis=axis, keepdims=True)

In [9]:
x = torch.randn(5, 3, requires_grad=False)
y = nn.Softmax()(x).numpy()
y_ = softmax(x.numpy(), axis=1)
print(y-y_)

[[ 3.7252903e-09 -7.4505806e-09  5.9604645e-08]
 [ 0.0000000e+00  2.9802322e-08  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00 -3.7252903e-09]
 [ 0.0000000e+00  2.9802322e-08 -2.9802322e-08]
 [ 0.0000000e+00  0.0000000e+00  2.9802322e-08]]


/home/geshi/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:1511: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)


# ReLU

In [10]:
def relu(x):
    return np.maximum(x, np.zeros_like(x))

In [11]:
x = torch.randn(5, requires_grad=False)
y = nn.ReLU()(x).numpy()
y_ = relu(x.numpy())
print(y-y_)

[0. 0. 0. 0. 0.]


# GLU

# GELU

# SiLU

# Swish

# SwiGLU